onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /cpu_ptb/DUT/fetch/clk
add wave -noupdate /cpu_ptb/DUT/fetch/rst_n
add wave -noupdate /cpu_ptb/DUT/fetch/stall
add wave -noupdate /cpu_ptb/DUT/fetch/flush
add wave -noupdate /cpu_ptb/DUT/fetch/branch_target
add wave -noupdate /cpu_ptb/DUT/fetch/pc
add wave -noupdate /cpu_ptb/DUT/fetch/F_out
add wave -noupdate /cpu_ptb/DUT/fetch/pc_next
add wave -noupdate /cpu_ptb/DUT/fetch/pc_plus_2
add wave -noupdate /cpu_ptb/DUT/fetch/instruction
add wave -noupdate /cpu_ptb/DUT/fetch/halt_PC
add wave -noupdate /cpu_ptb/DUT/decode/clk
add wave -noupdate /cpu_ptb/DUT/decode/rst_n
add wave -noupdate /cpu_ptb/DUT/decode/D_in
add wave -noupdate /cpu_ptb/DUT/decode/write_data_W
add wave -noupdate /cpu_ptb/DUT/decode/wr_reg_W
add wave -noupdate /cpu_ptb/DUT/decode/RegWrite_W
add wave -noupdate /cpu_ptb/DUT/decode/flush
add wave -noupdate /cpu_ptb/DUT/decode/branch_target
add wave -noupdate /cpu_ptb/DUT/decode/D_out
add wave -noupdate /cpu_ptb/DUT/decode/pc_plus_2_F
add wave -noupdate /cpu_ptb/DUT/decode/instruction_F
add wave -noupdate /cpu_ptb/DUT/decode/rr1_reg_D
add wave -noupdate /cpu_ptb/DUT/decode/rr2_reg_D
add wave -noupdate /cpu_ptb/DUT/decode/wr_reg_D
add wave -noupdate /cpu_ptb/DUT/decode/rr1_data_D
add wave -noupdate /cpu_ptb/DUT/decode/rr2_data_D
add wave -noupdate /cpu_ptb/DUT/decode/imm_value_D
add wave -noupdate /cpu_ptb/DUT/decode/RR1Mux_D
add wave -noupdate /cpu_ptb/DUT/decode/RR2Mux_D
add wave -noupdate /cpu_ptb/DUT/decode/ImmMux_D
add wave -noupdate /cpu_ptb/DUT/decode/ALUSrcMux_D
add wave -noupdate /cpu_ptb/DUT/decode/MemtoRegMux_D
add wave -noupdate /cpu_ptb/DUT/decode/PCSMux_D
add wave -noupdate /cpu_ptb/DUT/decode/HaltMux_D
add wave -noupdate /cpu_ptb/DUT/decode/BranchRegMux_D
add wave -noupdate /cpu_ptb/DUT/decode/BranchMux_D
add wave -noupdate /cpu_ptb/DUT/decode/RegWrite_D
add wave -noupdate /cpu_ptb/DUT/decode/MemWrite_D
add wave -noupdate /cpu_ptb/DUT/decode/MemRead_D
add wave -noupdate /cpu_ptb/DUT/decode/Flag_Enable_D
add wave -noupdate /cpu_ptb/DUT/decode/ALUop_D
add wave -noupdate /cpu_ptb/DUT/decode/branch_taken
add wave -noupdate /cpu_ptb/DUT/decode/extended_imm
add wave -noupdate /cpu_ptb/DUT/decode/branch_imm
add wave -noupdate /cpu_ptb/DUT/decode/halt_PC
add wave -noupdate /cpu_ptb/DUT/execute/clk
add wave -noupdate /cpu_ptb/DUT/execute/rst_n
add wave -noupdate /cpu_ptb/DUT/execute/X_in
add wave -noupdate /cpu_ptb/DUT/execute/X_out
add wave -noupdate /cpu_ptb/DUT/execute/wr_reg_X
add wave -noupdate /cpu_ptb/DUT/execute/rr2_reg_X
add wave -noupdate /cpu_ptb/DUT/execute/rr1_reg_X
add wave -noupdate /cpu_ptb/DUT/execute/imm_value_X
add wave -noupdate /cpu_ptb/DUT/execute/write_data_X
add wave -noupdate /cpu_ptb/DUT/execute/rr2_data_X
add wave -noupdate /cpu_ptb/DUT/execute/rr1_data_X
add wave -noupdate /cpu_ptb/DUT/execute/HaltMux_X
add wave -noupdate /cpu_ptb/DUT/execute/Flag_Enable_X
add wave -noupdate /cpu_ptb/DUT/execute/MemRead_X
add wave -noupdate /cpu_ptb/DUT/execute/MemWrite_X
add wave -noupdate /cpu_ptb/DUT/execute/RegWrite_X
add wave -noupdate /cpu_ptb/DUT/execute/MemtoRegMux_X
add wave -noupdate /cpu_ptb/DUT/execute/ALUSrcMux_X
add wave -noupdate /cpu_ptb/DUT/execute/ALUop_X
add wave -noupdate /cpu_ptb/DUT/execute/alu_input_b
add wave -noupdate /cpu_ptb/DUT/execute/alu_result
add wave -noupdate /cpu_ptb/DUT/execute/flags
add wave -noupdate /cpu_ptb/DUT/memory/clk
add wave -noupdate /cpu_ptb/DUT/memory/rst_n
add wave -noupdate /cpu_ptb/DUT/memory/M_in
add wave -noupdate /cpu_ptb/DUT/memory/M_out
add wave -noupdate /cpu_ptb/DUT/memory/wr_reg_M
add wave -noupdate /cpu_ptb/DUT/memory/alu_result
add wave -noupdate /cpu_ptb/DUT/memory/rr2_data_M
add wave -noupdate /cpu_ptb/DUT/memory/MemRead_M
add wave -noupdate /cpu_ptb/DUT/memory/MemWrite_M
add wave -noupdate /cpu_ptb/DUT/memory/RegWrite_M
add wave -noupdate /cpu_ptb/DUT/memory/MemtoRegMux_M
add wave -noupdate /cpu_ptb/DUT/memory/HaltMux_M
add wave -noupdate /cpu_ptb/DUT/memory/mem_data_out
add wave -noupdate /cpu_ptb/DUT/writeback/W_in
add wave -noupdate /cpu_ptb/DUT/writeback/HaltMux_W
add wave -noupdate /cpu_ptb/DUT/writeback/RegWrite_W
add wave -noupdate /cpu_ptb/DUT/writeback/write_data_W
add wave -noupdate /cpu_ptb/DUT/writeback/wr_reg_W
add wave -noupdate /cpu_ptb/DUT/writeback/alu_result
add wave -noupdate /cpu_ptb/DUT/writeback/mem_data_out
add wave -noupdate /cpu_ptb/DUT/writeback/MemtoRegMux_W
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1703600 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 253
configure wave -valuecolwidth 90
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {640 ns} {1920 ns}
